#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
UNIT_TEMPLATE="$REPO_DIR/deploy/claude-usage.service.in"
UNIT_PATH="$HOME/.config/systemd/user/claude-usage.service"

escape_sed() {
  printf '%s' "$1" | sed 's/[\\\/&]/\\&/g'
}

# Escape quoted systemd values; ExecStart also expands dollar signs.
unit_value() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//%/%%}"
  if [[ "${2:-}" == exec ]]; then value="${value//\$/\$\$}"; fi
  printf '%s' "$value"
}

DEFAULT_CREDENTIALS_FILE="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/.credentials.json"
DEFAULT_LISTEN_ADDR="0.0.0.0:55667"
DEFAULT_PROXY_URL="http://127.0.0.1:7890"

TOTAL_STAGES=3

banner "Install Claude Code usage systemd service"

stage "检查构建产物和安装条件"
say "这个向导会为当前用户安装 systemd user service，并让它在用户会话启动时自动启动。"
if [[ "$EUID" -eq 0 ]]; then
  warn "请使用已安装 Go 和 Claude Code 的普通用户运行 task，不要使用 root。"
  exit 1
fi
step "确认项目目录存在：$REPO_DIR"
if [[ ! -x "$REPO_DIR/build/claude-usage" ]]; then
  warn "未找到可执行文件：$REPO_DIR/build/claude-usage"
  say "请先运行：task build:claude-usage"
  exit 1
fi
if [[ ! -f "$UNIT_TEMPLATE" ]]; then
  warn "未找到 service 模板：$UNIT_TEMPLATE"
  exit 1
fi
if ! command -v systemctl >/dev/null 2>&1; then
  warn "未找到 systemctl；无法安装 user service。"
  exit 1
fi
pause "检查完成后按 Enter 继续"

stage "填写服务配置"
ask CREDENTIALS_FILE "Claude Code 凭据文件路径（默认：$DEFAULT_CREDENTIALS_FILE）："
CREDENTIALS_FILE="${CREDENTIALS_FILE:-$DEFAULT_CREDENTIALS_FILE}"
if [[ "$CREDENTIALS_FILE" == '~/'* ]]; then
  CREDENTIALS_FILE="$HOME/${CREDENTIALS_FILE:2}"
fi
if [[ ! -f "$CREDENTIALS_FILE" || ! -r "$CREDENTIALS_FILE" ]]; then
  warn "凭据文件不存在或不可读：$CREDENTIALS_FILE"
  say "请先使用 Claude Code 完成登录，或填写已有凭据文件路径。"
  exit 1
fi
CREDENTIALS_FILE="$(realpath -- "$CREDENTIALS_FILE")"

ask LISTEN_ADDR "监听地址（默认：$DEFAULT_LISTEN_ADDR）："
LISTEN_ADDR="${LISTEN_ADDR:-$DEFAULT_LISTEN_ADDR}"
ask PROXY_URL "HTTP/HTTPS 代理地址（默认：$DEFAULT_PROXY_URL）："
PROXY_URL="${PROXY_URL:-$DEFAULT_PROXY_URL}"
HOME_DIR="$HOME"

for value in "$REPO_DIR" "$HOME_DIR" "$CREDENTIALS_FILE" "$LISTEN_ADDR" "$PROXY_URL"; do
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    warn "配置值不能包含换行符。"
    exit 1
  fi
done

note "项目目录：$REPO_DIR"
note "服务用户：$USER"
note "凭据文件：$CREDENTIALS_FILE"
note "监听地址：$LISTEN_ADDR"
note "代理地址：$PROXY_URL"
pause "配置确认后按 Enter 继续"

stage "安装并启用 systemd user service"
if ! confirm "现在安装并启动当前用户的 claude-usage.service 吗？"; then
  warn "已取消；没有修改 user service。"
  exit 0
fi

TMP_UNIT="$(mktemp --suffix=.service)"
trap 'rm -f "$TMP_UNIT"' EXIT
sed \
  -e "s/@EXECUTABLE@/$(escape_sed "$(unit_value "$REPO_DIR/build/claude-usage" exec)")/g" \
  -e "s/@PROJECT_DIR@/$(escape_sed "${REPO_DIR//%/%%}")/g" \
  -e "s/@HOME_DIR@/$(escape_sed "$(unit_value "$HOME_DIR")")/g" \
  -e "s/@PROXY_URL@/$(escape_sed "$(unit_value "$PROXY_URL")")/g" \
  -e "s/@LISTEN_ADDR@/$(escape_sed "$(unit_value "$LISTEN_ADDR" exec)")/g" \
  -e "s/@CREDENTIALS_FILE@/$(escape_sed "$(unit_value "$CREDENTIALS_FILE" exec)")/g" \
  "$UNIT_TEMPLATE" > "$TMP_UNIT"

if command -v systemd-analyze >/dev/null 2>&1; then
  systemd-analyze --user verify "$TMP_UNIT"
fi
install -D -m 0644 "$TMP_UNIT" "$UNIT_PATH"
systemctl --user daemon-reload
systemctl --user enable claude-usage.service
systemctl --user restart claude-usage.service
say "user service 已安装并设置为用户会话启动时自动启动。"
note "查看状态：systemctl --user status claude-usage.service"
note "查看日志：journalctl --user -u claude-usage.service -f"
# ──────────────────────────────────────────────────────────────────────────

finish
